// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: protocols.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushMessage_MessageType int32

const (
	PushMessage_UNSPECIFIED PushMessage_MessageType = 0
	PushMessage_BROADCAST   PushMessage_MessageType = 1
	PushMessage_SUBSCRIBE   PushMessage_MessageType = 2
	PushMessage_UNSUBSCRIBE PushMessage_MessageType = 3
)

// Enum value maps for PushMessage_MessageType.
var (
	PushMessage_MessageType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "BROADCAST",
		2: "SUBSCRIBE",
		3: "UNSUBSCRIBE",
	}
	PushMessage_MessageType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"BROADCAST":   1,
		"SUBSCRIBE":   2,
		"UNSUBSCRIBE": 3,
	}
)

func (x PushMessage_MessageType) Enum() *PushMessage_MessageType {
	p := new(PushMessage_MessageType)
	*p = x
	return p
}

func (x PushMessage_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushMessage_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocols_proto_enumTypes[0].Descriptor()
}

func (PushMessage_MessageType) Type() protoreflect.EnumType {
	return &file_protocols_proto_enumTypes[0]
}

func (x PushMessage_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushMessage_MessageType.Descriptor instead.
func (PushMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{8, 0}
}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*Response_Success
	//	*Response_Error
	//	*Response_SubscriptionsResponse
	//	*Response_AddrResponse
	//	*Response_PostBondResponse
	//	*Response_AvailableMeshNodesResponse
	Response      isResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_protocols_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetResponse() isResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Response) GetSuccess() *Success {
	if x != nil {
		if x, ok := x.Response.(*Response_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *Response) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*Response_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Response) GetSubscriptionsResponse() *SubscriptionsResponse {
	if x != nil {
		if x, ok := x.Response.(*Response_SubscriptionsResponse); ok {
			return x.SubscriptionsResponse
		}
	}
	return nil
}

func (x *Response) GetAddrResponse() *ClientAddrResponse {
	if x != nil {
		if x, ok := x.Response.(*Response_AddrResponse); ok {
			return x.AddrResponse
		}
	}
	return nil
}

func (x *Response) GetPostBondResponse() *PostBondResponse {
	if x != nil {
		if x, ok := x.Response.(*Response_PostBondResponse); ok {
			return x.PostBondResponse
		}
	}
	return nil
}

func (x *Response) GetAvailableMeshNodesResponse() *AvailableMeshNodesResponse {
	if x != nil {
		if x, ok := x.Response.(*Response_AvailableMeshNodesResponse); ok {
			return x.AvailableMeshNodesResponse
		}
	}
	return nil
}

type isResponse_Response interface {
	isResponse_Response()
}

type Response_Success struct {
	Success *Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type Response_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type Response_SubscriptionsResponse struct {
	SubscriptionsResponse *SubscriptionsResponse `protobuf:"bytes,3,opt,name=subscriptions_response,json=subscriptionsResponse,proto3,oneof"`
}

type Response_AddrResponse struct {
	AddrResponse *ClientAddrResponse `protobuf:"bytes,4,opt,name=addr_response,json=addrResponse,proto3,oneof"`
}

type Response_PostBondResponse struct {
	PostBondResponse *PostBondResponse `protobuf:"bytes,5,opt,name=post_bond_response,json=postBondResponse,proto3,oneof"`
}

type Response_AvailableMeshNodesResponse struct {
	AvailableMeshNodesResponse *AvailableMeshNodesResponse `protobuf:"bytes,6,opt,name=available_mesh_nodes_response,json=availableMeshNodesResponse,proto3,oneof"`
}

func (*Response_Success) isResponse_Response() {}

func (*Response_Error) isResponse_Response() {}

func (*Response_SubscriptionsResponse) isResponse_Response() {}

func (*Response_AddrResponse) isResponse_Response() {}

func (*Response_PostBondResponse) isResponse_Response() {}

func (*Response_AvailableMeshNodesResponse) isResponse_Response() {}

type Success struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Success) Reset() {
	*x = Success{}
	mi := &file_protocols_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Success) ProtoMessage() {}

func (x *Success) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Success.ProtoReflect.Descriptor instead.
func (*Success) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{1}
}

// UnauthorizedError is returned when making a request on a protocol for which
// the peer is not authorized.
type UnauthorizedError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnauthorizedError) Reset() {
	*x = UnauthorizedError{}
	mi := &file_protocols_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnauthorizedError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnauthorizedError) ProtoMessage() {}

func (x *UnauthorizedError) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnauthorizedError.ProtoReflect.Descriptor instead.
func (*UnauthorizedError) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{2}
}

// CounterpartyNotFoundError is returned during a client initiate relay request
// to indicate that the relay was unable to be setup because the counterparty
// was not found.
type CounterpartyNotFoundError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterpartyNotFoundError) Reset() {
	*x = CounterpartyNotFoundError{}
	mi := &file_protocols_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterpartyNotFoundError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterpartyNotFoundError) ProtoMessage() {}

func (x *CounterpartyNotFoundError) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterpartyNotFoundError.ProtoReflect.Descriptor instead.
func (*CounterpartyNotFoundError) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{3}
}

// CounterpartyRejectedError is returned during a client initiate relay request
// to indicate that the relay was unable to be setup because the counterparty
// rejected the relay request.
type CounterpartyRejectedError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterpartyRejectedError) Reset() {
	*x = CounterpartyRejectedError{}
	mi := &file_protocols_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterpartyRejectedError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterpartyRejectedError) ProtoMessage() {}

func (x *CounterpartyRejectedError) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterpartyRejectedError.ProtoReflect.Descriptor instead.
func (*CounterpartyRejectedError) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{4}
}

// PostBondError is a type containing specific error information for the
// PostBonds protocol.
type PostBondError struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InvalidBondIndex uint32                 `protobuf:"varint,1,opt,name=invalidBondIndex,proto3" json:"invalidBondIndex,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PostBondError) Reset() {
	*x = PostBondError{}
	mi := &file_protocols_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBondError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBondError) ProtoMessage() {}

func (x *PostBondError) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBondError.ProtoReflect.Descriptor instead.
func (*PostBondError) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{5}
}

func (x *PostBondError) GetInvalidBondIndex() uint32 {
	if x != nil {
		return x.InvalidBondIndex
	}
	return 0
}

type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Error:
	//
	//	*Error_Unauthorized
	//	*Error_PostBondError
	//	*Error_Message
	//	*Error_CpNotFoundError
	//	*Error_CpRejectedError
	Error         isError_Error `protobuf_oneof:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_protocols_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetError() isError_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Error) GetUnauthorized() *UnauthorizedError {
	if x != nil {
		if x, ok := x.Error.(*Error_Unauthorized); ok {
			return x.Unauthorized
		}
	}
	return nil
}

func (x *Error) GetPostBondError() *PostBondError {
	if x != nil {
		if x, ok := x.Error.(*Error_PostBondError); ok {
			return x.PostBondError
		}
	}
	return nil
}

func (x *Error) GetMessage() string {
	if x != nil {
		if x, ok := x.Error.(*Error_Message); ok {
			return x.Message
		}
	}
	return ""
}

func (x *Error) GetCpNotFoundError() *CounterpartyNotFoundError {
	if x != nil {
		if x, ok := x.Error.(*Error_CpNotFoundError); ok {
			return x.CpNotFoundError
		}
	}
	return nil
}

func (x *Error) GetCpRejectedError() *CounterpartyRejectedError {
	if x != nil {
		if x, ok := x.Error.(*Error_CpRejectedError); ok {
			return x.CpRejectedError
		}
	}
	return nil
}

type isError_Error interface {
	isError_Error()
}

type Error_Unauthorized struct {
	Unauthorized *UnauthorizedError `protobuf:"bytes,1,opt,name=unauthorized,proto3,oneof"`
}

type Error_PostBondError struct {
	PostBondError *PostBondError `protobuf:"bytes,2,opt,name=post_bond_error,json=postBondError,proto3,oneof"`
}

type Error_Message struct {
	Message string `protobuf:"bytes,3,opt,name=message,proto3,oneof"`
}

type Error_CpNotFoundError struct {
	CpNotFoundError *CounterpartyNotFoundError `protobuf:"bytes,4,opt,name=cp_not_found_error,json=cpNotFoundError,proto3,oneof"`
}

type Error_CpRejectedError struct {
	CpRejectedError *CounterpartyRejectedError `protobuf:"bytes,5,opt,name=cp_rejected_error,json=cpRejectedError,proto3,oneof"`
}

func (*Error_Unauthorized) isError_Error() {}

func (*Error_PostBondError) isError_Error() {}

func (*Error_Message) isError_Error() {}

func (*Error_CpNotFoundError) isError_Error() {}

func (*Error_CpRejectedError) isError_Error() {}

// PublishRequest is sent by a client to publish a message to a topic.
type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_protocols_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{7}
}

func (x *PublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// PushMessage is sent by the server to push a message to a subscribed client.
// Used with the PushProtocol.
type PushMessage struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	MessageType   PushMessage_MessageType `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=pb.PushMessage_MessageType" json:"message_type,omitempty"`
	Topic         string                  `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Data          []byte                  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`     // Only populated for BROADCAST messages
	Sender        []byte                  `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"` // The peer who sent the message or performed the subscription action
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessage) Reset() {
	*x = PushMessage{}
	mi := &file_protocols_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessage) ProtoMessage() {}

func (x *PushMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessage.ProtoReflect.Descriptor instead.
func (*PushMessage) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{8}
}

func (x *PushMessage) GetMessageType() PushMessage_MessageType {
	if x != nil {
		return x.MessageType
	}
	return PushMessage_UNSPECIFIED
}

func (x *PushMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PushMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PushMessage) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

// SubscribeRequest is sent by a client to subscribe to topics.
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_protocols_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

// UnsubscribeRequest is sent by a client to unsubscribe from topics.
type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_protocols_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{10}
}

func (x *UnsubscribeRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

// SubscriptionsResponse is sent by a tatanka node informing the client
// which topics they are subscribed to.
type SubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionsResponse) Reset() {
	*x = SubscriptionsResponse{}
	mi := &file_protocols_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionsResponse) ProtoMessage() {}

func (x *SubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{11}
}

func (x *SubscriptionsResponse) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

// ClientAddrRequest is sent by a client to request the addresses of another peer.
type ClientAddrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // peer.ID serialized as bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientAddrRequest) Reset() {
	*x = ClientAddrRequest{}
	mi := &file_protocols_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAddrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAddrRequest) ProtoMessage() {}

func (x *ClientAddrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAddrRequest.ProtoReflect.Descriptor instead.
func (*ClientAddrRequest) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{12}
}

func (x *ClientAddrRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

// ClientAddrResponse is the response containing the multiaddresses of a peer or an error.
// Used with the ClientAddr.
type ClientAddrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addrs         [][]byte               `protobuf:"bytes,1,rep,name=addrs,proto3" json:"addrs,omitempty"` // multiaddrs serialized as bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientAddrResponse) Reset() {
	*x = ClientAddrResponse{}
	mi := &file_protocols_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAddrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAddrResponse) ProtoMessage() {}

func (x *ClientAddrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAddrResponse.ProtoReflect.Descriptor instead.
func (*ClientAddrResponse) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{13}
}

func (x *ClientAddrResponse) GetAddrs() [][]byte {
	if x != nil {
		return x.Addrs
	}
	return nil
}

// TODO: Delete assetID field?
type Bond struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetID       uint32                 `protobuf:"varint,1,opt,name=assetID,proto3" json:"assetID,omitempty"`
	BondID        []byte                 `protobuf:"bytes,2,opt,name=bondID,proto3" json:"bondID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bond) Reset() {
	*x = Bond{}
	mi := &file_protocols_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bond) ProtoMessage() {}

func (x *Bond) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bond.ProtoReflect.Descriptor instead.
func (*Bond) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{14}
}

func (x *Bond) GetAssetID() uint32 {
	if x != nil {
		return x.AssetID
	}
	return 0
}

func (x *Bond) GetBondID() []byte {
	if x != nil {
		return x.BondID
	}
	return nil
}

type PostBondRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bonds         []*Bond                `protobuf:"bytes,1,rep,name=bonds,proto3" json:"bonds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostBondRequest) Reset() {
	*x = PostBondRequest{}
	mi := &file_protocols_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBondRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBondRequest) ProtoMessage() {}

func (x *PostBondRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBondRequest.ProtoReflect.Descriptor instead.
func (*PostBondRequest) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{15}
}

func (x *PostBondRequest) GetBonds() []*Bond {
	if x != nil {
		return x.Bonds
	}
	return nil
}

type PostBondResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BondStrength  uint32                 `protobuf:"varint,1,opt,name=bondStrength,proto3" json:"bondStrength,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostBondResponse) Reset() {
	*x = PostBondResponse{}
	mi := &file_protocols_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBondResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBondResponse) ProtoMessage() {}

func (x *PostBondResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBondResponse.ProtoReflect.Descriptor instead.
func (*PostBondResponse) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{16}
}

func (x *PostBondResponse) GetBondStrength() uint32 {
	if x != nil {
		return x.BondStrength
	}
	return 0
}

// PeerInfo contains information about a single peer.
type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`       // peer.ID serialized as bytes
	Addrs         [][]byte               `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"` // multiaddrs serialized as bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_protocols_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{17}
}

func (x *PeerInfo) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PeerInfo) GetAddrs() [][]byte {
	if x != nil {
		return x.Addrs
	}
	return nil
}

// ClientRelayMessageRequest is a client originating request to send a
// message to another client.
type ClientRelayMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerID        []byte                 `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"` // peer.ID serialized as bytes
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRelayMessageRequest) Reset() {
	*x = ClientRelayMessageRequest{}
	mi := &file_protocols_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRelayMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRelayMessageRequest) ProtoMessage() {}

func (x *ClientRelayMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRelayMessageRequest.ProtoReflect.Descriptor instead.
func (*ClientRelayMessageRequest) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{18}
}

func (x *ClientRelayMessageRequest) GetPeerID() []byte {
	if x != nil {
		return x.PeerID
	}
	return nil
}

func (x *ClientRelayMessageRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

// ClientRelayMessageResponse is the response to a ClientRelayMessageRequest.
type ClientRelayMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ClientRelayMessageResponse_Message
	//	*ClientRelayMessageResponse_Error
	Response      isClientRelayMessageResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRelayMessageResponse) Reset() {
	*x = ClientRelayMessageResponse{}
	mi := &file_protocols_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRelayMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRelayMessageResponse) ProtoMessage() {}

func (x *ClientRelayMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRelayMessageResponse.ProtoReflect.Descriptor instead.
func (*ClientRelayMessageResponse) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{19}
}

func (x *ClientRelayMessageResponse) GetResponse() isClientRelayMessageResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ClientRelayMessageResponse) GetMessage() []byte {
	if x != nil {
		if x, ok := x.Response.(*ClientRelayMessageResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ClientRelayMessageResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*ClientRelayMessageResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isClientRelayMessageResponse_Response interface {
	isClientRelayMessageResponse_Response()
}

type ClientRelayMessageResponse_Message struct {
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type ClientRelayMessageResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ClientRelayMessageResponse_Message) isClientRelayMessageResponse_Response() {}

func (*ClientRelayMessageResponse_Error) isClientRelayMessageResponse_Response() {}

// TatankaRelayMessageRequest is a tatanka node originating request to a client
// to notify them that another client is sending them a message.
type TatankaRelayMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerID        []byte                 `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"` // peer.ID serialized as bytes
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TatankaRelayMessageRequest) Reset() {
	*x = TatankaRelayMessageRequest{}
	mi := &file_protocols_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TatankaRelayMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TatankaRelayMessageRequest) ProtoMessage() {}

func (x *TatankaRelayMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TatankaRelayMessageRequest.ProtoReflect.Descriptor instead.
func (*TatankaRelayMessageRequest) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{20}
}

func (x *TatankaRelayMessageRequest) GetPeerID() []byte {
	if x != nil {
		return x.PeerID
	}
	return nil
}

func (x *TatankaRelayMessageRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

// TatankaRelayMessageResponse is the response to a TatankaRelayMessageRequest.
type TatankaRelayMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*TatankaRelayMessageResponse_Message
	//	*TatankaRelayMessageResponse_Error
	Response      isTatankaRelayMessageResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TatankaRelayMessageResponse) Reset() {
	*x = TatankaRelayMessageResponse{}
	mi := &file_protocols_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TatankaRelayMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TatankaRelayMessageResponse) ProtoMessage() {}

func (x *TatankaRelayMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TatankaRelayMessageResponse.ProtoReflect.Descriptor instead.
func (*TatankaRelayMessageResponse) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{21}
}

func (x *TatankaRelayMessageResponse) GetResponse() isTatankaRelayMessageResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *TatankaRelayMessageResponse) GetMessage() []byte {
	if x != nil {
		if x, ok := x.Response.(*TatankaRelayMessageResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *TatankaRelayMessageResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*TatankaRelayMessageResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isTatankaRelayMessageResponse_Response interface {
	isTatankaRelayMessageResponse_Response()
}

type TatankaRelayMessageResponse_Message struct {
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type TatankaRelayMessageResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*TatankaRelayMessageResponse_Message) isTatankaRelayMessageResponse_Response() {}

func (*TatankaRelayMessageResponse_Error) isTatankaRelayMessageResponse_Response() {}

// AvailableMeshNodesRequest is sent by a client to get a list of all mesh
// nodes that the tatanka node is connected to.
type AvailableMeshNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableMeshNodesRequest) Reset() {
	*x = AvailableMeshNodesRequest{}
	mi := &file_protocols_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableMeshNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableMeshNodesRequest) ProtoMessage() {}

func (x *AvailableMeshNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableMeshNodesRequest.ProtoReflect.Descriptor instead.
func (*AvailableMeshNodesRequest) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{22}
}

// AvailableMeshNodesResponse contains a list of all whitelisted mesh nodes
// that this tatanka node is connected to, including itself.
type AvailableMeshNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableMeshNodesResponse) Reset() {
	*x = AvailableMeshNodesResponse{}
	mi := &file_protocols_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableMeshNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableMeshNodesResponse) ProtoMessage() {}

func (x *AvailableMeshNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableMeshNodesResponse.ProtoReflect.Descriptor instead.
func (*AvailableMeshNodesResponse) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{23}
}

func (x *AvailableMeshNodesResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

// InitialSubscriptions is sent by the client as the first message when
// establishing a push stream. It contains the list of topics the client
// is currently subscribed to.
type InitialSubscriptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialSubscriptions) Reset() {
	*x = InitialSubscriptions{}
	mi := &file_protocols_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialSubscriptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialSubscriptions) ProtoMessage() {}

func (x *InitialSubscriptions) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialSubscriptions.ProtoReflect.Descriptor instead.
func (*InitialSubscriptions) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{24}
}

func (x *InitialSubscriptions) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

// Price represents a single ticker-price pair for client consumption.
type ClientPriceUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prices        map[string]float32     `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientPriceUpdate) Reset() {
	*x = ClientPriceUpdate{}
	mi := &file_protocols_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPriceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPriceUpdate) ProtoMessage() {}

func (x *ClientPriceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPriceUpdate.ProtoReflect.Descriptor instead.
func (*ClientPriceUpdate) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{25}
}

func (x *ClientPriceUpdate) GetPrices() map[string]float32 {
	if x != nil {
		return x.Prices
	}
	return nil
}

// ClientFeeRateUpdate represents a network-fee rate update for client consumption.
type ClientFeeRateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeeRate       []byte                 `protobuf:"bytes,1,opt,name=fee_rate,json=feeRate,proto3" json:"fee_rate,omitempty"` // big-endian encoded big integer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFeeRateUpdate) Reset() {
	*x = ClientFeeRateUpdate{}
	mi := &file_protocols_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFeeRateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFeeRateUpdate) ProtoMessage() {}

func (x *ClientFeeRateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFeeRateUpdate.ProtoReflect.Descriptor instead.
func (*ClientFeeRateUpdate) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{26}
}

func (x *ClientFeeRateUpdate) GetFeeRate() []byte {
	if x != nil {
		return x.FeeRate
	}
	return nil
}

// ClientOracleUpdate contains oracle data for clients.
type ClientOracleUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*ClientOracleUpdate_PriceUpdate
	//	*ClientOracleUpdate_FeeRateUpdate
	Update        isClientOracleUpdate_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientOracleUpdate) Reset() {
	*x = ClientOracleUpdate{}
	mi := &file_protocols_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientOracleUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientOracleUpdate) ProtoMessage() {}

func (x *ClientOracleUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientOracleUpdate.ProtoReflect.Descriptor instead.
func (*ClientOracleUpdate) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{27}
}

func (x *ClientOracleUpdate) GetUpdate() isClientOracleUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *ClientOracleUpdate) GetPriceUpdate() *ClientPriceUpdate {
	if x != nil {
		if x, ok := x.Update.(*ClientOracleUpdate_PriceUpdate); ok {
			return x.PriceUpdate
		}
	}
	return nil
}

func (x *ClientOracleUpdate) GetFeeRateUpdate() *ClientFeeRateUpdate {
	if x != nil {
		if x, ok := x.Update.(*ClientOracleUpdate_FeeRateUpdate); ok {
			return x.FeeRateUpdate
		}
	}
	return nil
}

type isClientOracleUpdate_Update interface {
	isClientOracleUpdate_Update()
}

type ClientOracleUpdate_PriceUpdate struct {
	PriceUpdate *ClientPriceUpdate `protobuf:"bytes,1,opt,name=price_update,json=priceUpdate,proto3,oneof"`
}

type ClientOracleUpdate_FeeRateUpdate struct {
	FeeRateUpdate *ClientFeeRateUpdate `protobuf:"bytes,2,opt,name=fee_rate_update,json=feeRateUpdate,proto3,oneof"`
}

func (*ClientOracleUpdate_PriceUpdate) isClientOracleUpdate_Update() {}

func (*ClientOracleUpdate_FeeRateUpdate) isClientOracleUpdate_Update() {}

// SearchTopicsRequest is sent by a client to search for topics in the mesh.
type SearchTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []string               `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTopicsRequest) Reset() {
	*x = SearchTopicsRequest{}
	mi := &file_protocols_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTopicsRequest) ProtoMessage() {}

func (x *SearchTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTopicsRequest.ProtoReflect.Descriptor instead.
func (*SearchTopicsRequest) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{28}
}

func (x *SearchTopicsRequest) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

// SearchTopicsResponse is sent by a tatanka node to a client with a list of
// topics that match the client's query.
type SearchTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTopicsResponse) Reset() {
	*x = SearchTopicsResponse{}
	mi := &file_protocols_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTopicsResponse) ProtoMessage() {}

func (x *SearchTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTopicsResponse.ProtoReflect.Descriptor instead.
func (*SearchTopicsResponse) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{29}
}

func (x *SearchTopicsResponse) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

var File_protocols_proto protoreflect.FileDescriptor

const file_protocols_proto_rawDesc = "" +
	"\n" +
	"\x0fprotocols.proto\x12\x02pb\"\xa0\x03\n" +
	"\bResponse\x12'\n" +
	"\asuccess\x18\x01 \x01(\v2\v.pb.SuccessH\x00R\asuccess\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\t.pb.ErrorH\x00R\x05error\x12R\n" +
	"\x16subscriptions_response\x18\x03 \x01(\v2\x19.pb.SubscriptionsResponseH\x00R\x15subscriptionsResponse\x12=\n" +
	"\raddr_response\x18\x04 \x01(\v2\x16.pb.ClientAddrResponseH\x00R\faddrResponse\x12D\n" +
	"\x12post_bond_response\x18\x05 \x01(\v2\x14.pb.PostBondResponseH\x00R\x10postBondResponse\x12c\n" +
	"\x1davailable_mesh_nodes_response\x18\x06 \x01(\v2\x1e.pb.AvailableMeshNodesResponseH\x00R\x1aavailableMeshNodesResponseB\n" +
	"\n" +
	"\bresponse\"\t\n" +
	"\aSuccess\"\x13\n" +
	"\x11UnauthorizedError\"\x1b\n" +
	"\x19CounterpartyNotFoundError\"\x1b\n" +
	"\x19CounterpartyRejectedError\";\n" +
	"\rPostBondError\x12*\n" +
	"\x10invalidBondIndex\x18\x01 \x01(\rR\x10invalidBondIndex\"\xc1\x02\n" +
	"\x05Error\x12;\n" +
	"\funauthorized\x18\x01 \x01(\v2\x15.pb.UnauthorizedErrorH\x00R\funauthorized\x12;\n" +
	"\x0fpost_bond_error\x18\x02 \x01(\v2\x11.pb.PostBondErrorH\x00R\rpostBondError\x12\x1a\n" +
	"\amessage\x18\x03 \x01(\tH\x00R\amessage\x12L\n" +
	"\x12cp_not_found_error\x18\x04 \x01(\v2\x1d.pb.CounterpartyNotFoundErrorH\x00R\x0fcpNotFoundError\x12K\n" +
	"\x11cp_rejected_error\x18\x05 \x01(\v2\x1d.pb.CounterpartyRejectedErrorH\x00R\x0fcpRejectedErrorB\a\n" +
	"\x05error\":\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xde\x01\n" +
	"\vPushMessage\x12>\n" +
	"\fmessage_type\x18\x01 \x01(\x0e2\x1b.pb.PushMessage.MessageTypeR\vmessageType\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\fR\x06sender\"M\n" +
	"\vMessageType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\r\n" +
	"\tBROADCAST\x10\x01\x12\r\n" +
	"\tSUBSCRIBE\x10\x02\x12\x0f\n" +
	"\vUNSUBSCRIBE\x10\x03\"*\n" +
	"\x10SubscribeRequest\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\",\n" +
	"\x12UnsubscribeRequest\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\"/\n" +
	"\x15SubscriptionsResponse\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\"#\n" +
	"\x11ClientAddrRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"*\n" +
	"\x12ClientAddrResponse\x12\x14\n" +
	"\x05addrs\x18\x01 \x03(\fR\x05addrs\"8\n" +
	"\x04Bond\x12\x18\n" +
	"\aassetID\x18\x01 \x01(\rR\aassetID\x12\x16\n" +
	"\x06bondID\x18\x02 \x01(\fR\x06bondID\"1\n" +
	"\x0fPostBondRequest\x12\x1e\n" +
	"\x05bonds\x18\x01 \x03(\v2\b.pb.BondR\x05bonds\"6\n" +
	"\x10PostBondResponse\x12\"\n" +
	"\fbondStrength\x18\x01 \x01(\rR\fbondStrength\"0\n" +
	"\bPeerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\fR\x05addrs\"M\n" +
	"\x19ClientRelayMessageRequest\x12\x16\n" +
	"\x06peerID\x18\x01 \x01(\fR\x06peerID\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\"g\n" +
	"\x1aClientRelayMessageResponse\x12\x1a\n" +
	"\amessage\x18\x01 \x01(\fH\x00R\amessage\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\t.pb.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"N\n" +
	"\x1aTatankaRelayMessageRequest\x12\x16\n" +
	"\x06peerID\x18\x01 \x01(\fR\x06peerID\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\"h\n" +
	"\x1bTatankaRelayMessageResponse\x12\x1a\n" +
	"\amessage\x18\x01 \x01(\fH\x00R\amessage\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\t.pb.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\x1b\n" +
	"\x19AvailableMeshNodesRequest\"@\n" +
	"\x1aAvailableMeshNodesResponse\x12\"\n" +
	"\x05peers\x18\x01 \x03(\v2\f.pb.PeerInfoR\x05peers\".\n" +
	"\x14InitialSubscriptions\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\"\x89\x01\n" +
	"\x11ClientPriceUpdate\x129\n" +
	"\x06prices\x18\x01 \x03(\v2!.pb.ClientPriceUpdate.PricesEntryR\x06prices\x1a9\n" +
	"\vPricesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"0\n" +
	"\x13ClientFeeRateUpdate\x12\x19\n" +
	"\bfee_rate\x18\x01 \x01(\fR\afeeRate\"\x9d\x01\n" +
	"\x12ClientOracleUpdate\x12:\n" +
	"\fprice_update\x18\x01 \x01(\v2\x15.pb.ClientPriceUpdateH\x00R\vpriceUpdate\x12A\n" +
	"\x0ffee_rate_update\x18\x02 \x01(\v2\x17.pb.ClientFeeRateUpdateH\x00R\rfeeRateUpdateB\b\n" +
	"\x06update\"/\n" +
	"\x13SearchTopicsRequest\x12\x18\n" +
	"\afilters\x18\x01 \x03(\tR\afilters\".\n" +
	"\x14SearchTopicsResponse\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topicsB)Z'github.com/bisoncraft/mesh/protocols/pbb\x06proto3"

var (
	file_protocols_proto_rawDescOnce sync.Once
	file_protocols_proto_rawDescData []byte
)

func file_protocols_proto_rawDescGZIP() []byte {
	file_protocols_proto_rawDescOnce.Do(func() {
		file_protocols_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocols_proto_rawDesc), len(file_protocols_proto_rawDesc)))
	})
	return file_protocols_proto_rawDescData
}

var file_protocols_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protocols_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_protocols_proto_goTypes = []any{
	(PushMessage_MessageType)(0),        // 0: pb.PushMessage.MessageType
	(*Response)(nil),                    // 1: pb.Response
	(*Success)(nil),                     // 2: pb.Success
	(*UnauthorizedError)(nil),           // 3: pb.UnauthorizedError
	(*CounterpartyNotFoundError)(nil),   // 4: pb.CounterpartyNotFoundError
	(*CounterpartyRejectedError)(nil),   // 5: pb.CounterpartyRejectedError
	(*PostBondError)(nil),               // 6: pb.PostBondError
	(*Error)(nil),                       // 7: pb.Error
	(*PublishRequest)(nil),              // 8: pb.PublishRequest
	(*PushMessage)(nil),                 // 9: pb.PushMessage
	(*SubscribeRequest)(nil),            // 10: pb.SubscribeRequest
	(*UnsubscribeRequest)(nil),          // 11: pb.UnsubscribeRequest
	(*SubscriptionsResponse)(nil),       // 12: pb.SubscriptionsResponse
	(*ClientAddrRequest)(nil),           // 13: pb.ClientAddrRequest
	(*ClientAddrResponse)(nil),          // 14: pb.ClientAddrResponse
	(*Bond)(nil),                        // 15: pb.Bond
	(*PostBondRequest)(nil),             // 16: pb.PostBondRequest
	(*PostBondResponse)(nil),            // 17: pb.PostBondResponse
	(*PeerInfo)(nil),                    // 18: pb.PeerInfo
	(*ClientRelayMessageRequest)(nil),   // 19: pb.ClientRelayMessageRequest
	(*ClientRelayMessageResponse)(nil),  // 20: pb.ClientRelayMessageResponse
	(*TatankaRelayMessageRequest)(nil),  // 21: pb.TatankaRelayMessageRequest
	(*TatankaRelayMessageResponse)(nil), // 22: pb.TatankaRelayMessageResponse
	(*AvailableMeshNodesRequest)(nil),   // 23: pb.AvailableMeshNodesRequest
	(*AvailableMeshNodesResponse)(nil),  // 24: pb.AvailableMeshNodesResponse
	(*InitialSubscriptions)(nil),        // 25: pb.InitialSubscriptions
	(*ClientPriceUpdate)(nil),           // 26: pb.ClientPriceUpdate
	(*ClientFeeRateUpdate)(nil),         // 27: pb.ClientFeeRateUpdate
	(*ClientOracleUpdate)(nil),          // 28: pb.ClientOracleUpdate
	(*SearchTopicsRequest)(nil),         // 29: pb.SearchTopicsRequest
	(*SearchTopicsResponse)(nil),        // 30: pb.SearchTopicsResponse
	nil,                                 // 31: pb.ClientPriceUpdate.PricesEntry
}
var file_protocols_proto_depIdxs = []int32{
	2,  // 0: pb.Response.success:type_name -> pb.Success
	7,  // 1: pb.Response.error:type_name -> pb.Error
	12, // 2: pb.Response.subscriptions_response:type_name -> pb.SubscriptionsResponse
	14, // 3: pb.Response.addr_response:type_name -> pb.ClientAddrResponse
	17, // 4: pb.Response.post_bond_response:type_name -> pb.PostBondResponse
	24, // 5: pb.Response.available_mesh_nodes_response:type_name -> pb.AvailableMeshNodesResponse
	3,  // 6: pb.Error.unauthorized:type_name -> pb.UnauthorizedError
	6,  // 7: pb.Error.post_bond_error:type_name -> pb.PostBondError
	4,  // 8: pb.Error.cp_not_found_error:type_name -> pb.CounterpartyNotFoundError
	5,  // 9: pb.Error.cp_rejected_error:type_name -> pb.CounterpartyRejectedError
	0,  // 10: pb.PushMessage.message_type:type_name -> pb.PushMessage.MessageType
	15, // 11: pb.PostBondRequest.bonds:type_name -> pb.Bond
	7,  // 12: pb.ClientRelayMessageResponse.error:type_name -> pb.Error
	7,  // 13: pb.TatankaRelayMessageResponse.error:type_name -> pb.Error
	18, // 14: pb.AvailableMeshNodesResponse.peers:type_name -> pb.PeerInfo
	31, // 15: pb.ClientPriceUpdate.prices:type_name -> pb.ClientPriceUpdate.PricesEntry
	26, // 16: pb.ClientOracleUpdate.price_update:type_name -> pb.ClientPriceUpdate
	27, // 17: pb.ClientOracleUpdate.fee_rate_update:type_name -> pb.ClientFeeRateUpdate
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_protocols_proto_init() }
func file_protocols_proto_init() {
	if File_protocols_proto != nil {
		return
	}
	file_protocols_proto_msgTypes[0].OneofWrappers = []any{
		(*Response_Success)(nil),
		(*Response_Error)(nil),
		(*Response_SubscriptionsResponse)(nil),
		(*Response_AddrResponse)(nil),
		(*Response_PostBondResponse)(nil),
		(*Response_AvailableMeshNodesResponse)(nil),
	}
	file_protocols_proto_msgTypes[6].OneofWrappers = []any{
		(*Error_Unauthorized)(nil),
		(*Error_PostBondError)(nil),
		(*Error_Message)(nil),
		(*Error_CpNotFoundError)(nil),
		(*Error_CpRejectedError)(nil),
	}
	file_protocols_proto_msgTypes[19].OneofWrappers = []any{
		(*ClientRelayMessageResponse_Message)(nil),
		(*ClientRelayMessageResponse_Error)(nil),
	}
	file_protocols_proto_msgTypes[21].OneofWrappers = []any{
		(*TatankaRelayMessageResponse_Message)(nil),
		(*TatankaRelayMessageResponse_Error)(nil),
	}
	file_protocols_proto_msgTypes[27].OneofWrappers = []any{
		(*ClientOracleUpdate_PriceUpdate)(nil),
		(*ClientOracleUpdate_FeeRateUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocols_proto_rawDesc), len(file_protocols_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocols_proto_goTypes,
		DependencyIndexes: file_protocols_proto_depIdxs,
		EnumInfos:         file_protocols_proto_enumTypes,
		MessageInfos:      file_protocols_proto_msgTypes,
	}.Build()
	File_protocols_proto = out.File
	file_protocols_proto_goTypes = nil
	file_protocols_proto_depIdxs = nil
}
